live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
title = "tedvo.dev"
dynamic_title = true
# dynamic_padding = true
opacity = 0.0
  [window.padding]
  x = 2
  y = 2

[font]
size = 12

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

  [colors.primary]
  background = "#1E1E2E" # base
  foreground = "#CDD6F4" # text

  # Bright and dim foreground colors
  dim_foreground = "#CDD6F4" # text
  bright_foreground = "#CDD6F4" # text

  [colors.cursor]
  text = "#1E1E2E" # base
  cursor = "#F5E0DC" # rosewater

  [colors.vi_mode_cursor]
  text = "#1E1E2E" # base
  cursor = "#B4BEFE" # lavender

  # Search colors
  [colors.search.matches]
  foreground = "#1E1E2E" # base
  background = "#A6ADC8" # subtext0

  [colors.search.focused_match]
  foreground = "#1E1E2E" # base
  background = "#A6E3A1" # green

  # Keyboard regex hints
  [colors.hints.start]
  foreground = "#1E1E2E" # base
  background = "#F9E2AF" # yellow
  
  [colors.hints.end]
  foreground = "#1E1E2E" # base
  background = "#A6ADC8" # subtext0

  [colors.selection]
  text = "#1E1E2E" # base
  background = "#F5E0DC" # rosewater

  [colors.normal]
  black = "#45475A" # surface1
  red = "#F38BA8" # red
  green = "#A6E3A1" # green
  yellow = "#F9E2AF" # yellow
  blue = "#89B4FA" # blue
  magenta = "#F5C2E7" # pink
  cyan = "#94E2D5" # teal
  white = "#BAC2DE" # subtext1

  [colors.bright]
  black = "#585B70" # surface2
  red = "#F38BA8" # red
  green = "#A6E3A1" # green
  yellow = "#F9E2AF" # yellow
  blue = "#89B4FA" # blue
  magenta = "#F5C2E7" # pink
  cyan = "#94E2D5" # teal
  white = "#A6ADC8" # subtext0

  [colors.dim]
  black = "#45475A" # surface1
  red = "#F38BA8" # red
  green = "#A6E3A1" # green
  yellow = "#F9E2AF" # yellow
  blue = "#89B4FA" # blue
  magenta = "#F5C2E7" # pink
  cyan = "#94E2D5" # teal
  white = "#BAC2DE" # subtext1
