live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
title = "TedVo"
dynamic_title = true
  [window.padding]
  x = 5
  y = 5

[font]
size = 14

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

  [colors.primary]
  background = "#121212"
  foreground = "#bdc1c6"

  [colors.selection]
  text = "CellBackground"
  background = "CellForeground"

  [colors.normal]
  black = "#1d3b53"
  red = "#fc514e"
  green = "#a1cd5e"
  yellow = "#e3d18a"
  blue = "#82aaff"
  magenta = "#c792ea"
  cyan = "#7fdbca"
  white = "#a1aab8"

  [colors.bright]
  black = "#7c8f8f"
  red = "#ff5874"
  green = "#21c7a8"
  yellow = "#ecc48d"
  blue = "#82aaff"
  magenta = "#ae81ff"
  cyan = "#7fdbca"
  white = "#d6deeb"
